### ISSUE TITLE
bri xtf

### ISSUE THREAD

**Issue by mathias7777** [mathiassantourian/wtfisthis#1]
![matashit](https://user-images.githubusercontent.com/46203446/111085338-4dbe6f00-8517-11eb-85c2-b77063418b79.jpg)
regarde, wtf is this

**Comment by mathias7777** [comment]
duplocait!

**Comment by mathias7777** [comment]
wukk i oez?

**Comment by mathiassantourian** [comment]
Z-FT HYW OID DYOU MAJDE YTIHQ?!ù

**Comment by mathiassantourian** [comment]
HJIOW DID YUOJU FINSIDE THIS UMPGFÉAG?§

**Comment by mathias7777** [comment]
i dont knsow...

**Comment by mathias7777** [comment]
here shoud q?

**Comment by mathiassantourian** [comment]
are we ain ds agrn?

**Comment by mathiassantourian** [comment]
we arent ion sles?.?..

**Comment by mathiassantourian** [comment]
maube senfd me aa mail pon, @mathias7777  ;,<

**Comment by mathias7777** [comment]
kkkkkkkkkkkk

**Comment by mathias7777** [comment]
will

**Comment by mathiassantourian** [comment]
bt<

**Comment by mathiassantourian** [comment]
le feu

**Comment by mathiassantourian** [comment]
u

**Comment by mathias7777** [comment]
never

**Comment by mathias7777** [comment]
wont

**Comment by mathias7777** [comment]
bc

**Comment by mathias7777** [comment]
this ez?

**Comment by mathiassantourian** [comment]
noi its not<

**Comment by mathiassantourian** [comment]
you will dire ion eyt ereijqSPRECIFU
![wow](https://user-images.githubusercontent.com/72752622/111085437-abeb5200-8517-11eb-9889-72f7d3706e6e.png)

**Comment by mathiassantourian** [comment]
reagrder cette image.

**Comment by mathias7777** [comment]
ONG

**Comment by mathias7777** [comment]
AS A MATASHI ADMINISTERATO, I THIKN I WILL BE ABLT PO TINHECT FOSM ERSQL I !!!!!

**Comment by mathiassantourian** [comment]
NO:! FDOIUHGN YHJID ID SSIUE  YPOJU FDOIEZ!!!

**Comment by mathias7777** [comment]
oka....

**Comment by mathias7777** [comment]
ca n we close thios nisssssssue now ?

**Comment by mathiassantourian** [comment]
ern,,,,,,,, sured!

**Comment by mathias7777** [comment]
tjhank yoju so mucj !!!!!!!

**Comment by mathiassantourian** [comment]
NON JRE LA RETOUE

**Comment by mathias7777** [comment]
WTF

**Comment by mathiassantourian** [comment]
OVIJU ANV AUCUJN FPOIUDQ!

**Comment by mathiassantourian** [comment]
aller vpoiu fai roi !!!

**Comment by mathias7777** [comment]
sywèu ?!

**Comment by mathiassantourian** [comment]
cqn,kyoi ujelt iyt ojplmn?./)()=tr

**Comment by mathiassantourian** [comment]
IFLC OUI!

**Comment by mathias7777** [comment]
OGKJ? !!!!!! NEBVER !:
